
SELECT * into xx_articulos FROM dbo.Hoja1$

alter table xx_articulos  add xx nvarchar(10)

 
UPDATE XX_ARTICULOS
SET UBICACION ='1'
WHERE ISNULL(UBICACION,'0')<>'0'

UPDATE XX_ARTICULOS
SET UBICACION ='2'
WHERE ISNULL(UBICACION,'0')='0'



SELECT LEFT(LTRIM(STR(CODIGO)),6),* FROM XX_ARTICULOS 
UPDATE XX_ARTICULOS
SET XX=LEFT(LTRIM(STR(CODIGO)),6)


SELECT * FROM MAEART
INSERT INTO MAEART (ACODIGO,ADESCRI,AUNIDAD,AFAMILIA)
SELECT XX, PRODUCTO,UNIDAD,UBICACION FROM XX_ARTICULOS
