SELECT CAST(CODIGO AS VARCHAR(6)),*  FROM dbo.HEXTOBRE

Select * from dbo.BOL112002

Select * From dbo.MOV052002

INUMBOL,CONCEPTO,MONTO,CODNOMBOL   


INSERT INTO MOV092002
Select INUMBOL,CONCEPTO='INGHEXTR',MONTO=ISNULL(SETIEMBRE,0) ,CODNOMBOL From BOL092002 A,HEXTOBRE B
WHERE A.CODTRAB=CAST(B.CODIGO AS VARCHAR(6)) 




SELECT * FROM  CAMTEX.DBO.MOV082002