SELECT * FROM (
SELECT A.CONCEPTO,DESCRICONCEP=B.NOMBRE,B.TIPO, 
       MONTO=SUM(ISNULL(A.MONTO,0)),
	   INGRESOS=CASE WHEN B.TIPO=1 THEN SUM(ISNULL(MONTO,0)) ELSE 0 END,
       EGRESOS=CASE WHEN B.TIPO=2 THEN SUM(ISNULL(MONTO,0)) ELSE 0 END,
       APORTA=CASE WHEN B.TIPO=3 THEN SUM(ISNULL(MONTO,0)) ELSE 0 END
FROM CAMTEX.DBO.MOV012003 A,
              CAMTEX.DBO.CONCEPTOS B              
WHERE A.CONCEPTO=B.CODIGO AND B.TIPO > 0 AND A.CODNOMBOL IN(29)
GROUP BY A.CONCEPTO,B.NOMBRE,B.TIPO

UNION ALL 
SELECT 
	  CONCEPTO='_SYSTEM',
      DESCRICONCEP='ADELANTO DE PAGO',
      TIPO=2, 
      MONTO=SUM(ISNULL(A.MONTO,0)),
	  INGRESOS=0,
      EGRESOS=SUM(ISNULL(A.MONTO,0)),
      APORTA=0      
FROM CAMTEX.DBO.ADEL2000  A
WHERE ORIGEN IN(29) 
GROUP BY A.ORIGEN 
UNION ALL

SELECT
	  CONCEPTO=CASE P.TIPO 
               WHEN 1 THEN '_OTROSIN'
               WHEN 2 THEN '_OTROSE' END,  
      DESCRICONCEP=CASE P.TIPO 
               WHEN 1 THEN 'INGRESOS(CTAS.CTES)'
               WHEN 2 THEN 'EGRESOS(CTAS.CTES.)' END,
      TIPO=P.TIPO, 
      MONTO=SUM(ISNULL(P.MONTO,0)),
	  INGRESOS=CASE WHEN P.TIPO=1 THEN SUM(ISNULL(P.MONTO,0)) ELSE 0 END,
      EGRESOS=CASE WHEN P.TIPO=2 THEN SUM(ISNULL(P.MONTO,0)) ELSE 0 END,
      APORTA=0
FROM CAMTEX.dbo.PAGOSCTA  P
WHERE P.CODNOMBOL IN (29) AND P.TIPOBOLETA='B'
GROUP BY P.TIPO ) AS X
ORDER BY X.CONCEPTO









--SELECT * FROM CAMTEX.DBO.CONCEPTOS

--SELECT * FROM CAMTEX.DBO.MOV012003