delete from te_cabecerarecibos where cabrec_numrecibo='200577'
delete from te_cabecerarecibos where cabrec_numrecibo='200581'
delete from te_cabecerarecibos where cabrec_numrecibo='200302'
delete from te_cabecerarecibos where cabrec_numrecibo='200578'
delete from te_cabecerarecibos where cabrec_numrecibo='200571'

delete from te_cabecerarecibos where cabrec_numrecibo='200323'
delete from te_cabecerarecibos where cabrec_numrecibo='200287'



select * from te_detallerecibos where cabrec_numrecibo='200577'
select * from te_detallerecibos where cabrec_numrecibo='200581'
select * from te_detallerecibos where cabrec_numrecibo='200302'
select * from te_detallerecibos where cabrec_numrecibo='200578'
select * from te_detallerecibos where cabrec_numrecibo='200571'

delete from cp_abono where documentoabono='01' and abononumdoc='00100035146'
delete from cp_abono where documentoabono='01' and abononumdoc='00100004981'
delete from cp_abono where documentoabono='01' and abononumdoc='00100011454'
delete from cp_abono where documentoabono='01' and abononumdoc='00120369'
delete from cp_abono where documentoabono='01' and abononumdoc='00100027888'
delete from cp_abono where documentoabono='01' and abononumdoc='00100027898'

delete from cp_abono where documentoabono='01' and abononumdoc='00200001514'
delete from cp_abono where documentoabono='01' and abononumdoc='00662855'
--delete from cp_abono where documentoabono='01' and abononumdoc='00200001514'


update cp_cargo set cargoapeimppag=0,cargoapeflgcan=0 where documentocargo='01' and cargonumdoc='00100035146'
update cp_cargo set cargoapeimppag=0,cargoapeflgcan=0 where documentocargo='01' and cargonumdoc='00100004981'
update cp_cargo set cargoapeimppag=0,cargoapeflgcan=0 where documentocargo='01' and cargonumdoc='00100011454'
update cp_cargo set cargoapeimppag=0,cargoapeflgcan=0 where documentocargo='01' and cargonumdoc='00120369'
update cp_cargo set cargoapeimppag=0,cargoapeflgcan=0 where documentocargo='01' and cargonumdoc='00100027888'
update cp_cargo set cargoapeimppag=0,cargoapeflgcan=0 where documentocargo='01' and cargonumdoc='00100027898'

update cp_cargo set cargoapeimppag=0,cargoapeflgcan=0 where documentocargo='01' and cargonumdoc='00200001514'
update cp_cargo set cargoapeimppag=0,cargoapeflgcan=0 where documentocargo='01' and cargonumdoc='00662855'

cabrec_numrecibo detrec_estadoreg detrec_item detrec_emisioncheque detrec_tipodoc_concepto detrec_numdocumento detrec_carabo detrec_forcan detrec_tdqc detrec_ndqc detrec_tipocajabanco detrec_cajabanco1 detrec_numctacte               detrec_adicionactacte detrec_monedadocumento detrec_monedacancela detrec_importesoles                                   detrec_importedolares                                 MOV_COD1 MOV_COD2 MOV_COD3 MOV_COD4 detrec_contadispo detrec_fechacancela                                    MOV_REFERE MOV_CENCOS detrec_observacion                                 usuariocodigo fechaact                                               
---------------- ---------------- ----------- -------------------- ----------------------- ------------------- ------------- ------------- ----------- ----------- -------------------- ----------------- ------------------------------ --------------------- ---------------------- -------------------- ----------------------------------------------------- ----------------------------------------------------- -------- -------- -------- -------- ----------------- ------------------------------------------------------ ---------- ---------- -------------------------------------------------- ------------- ------------------------------------------------------ 
200577                            1           B                    01                      00100035146         A             T             59          7061478     B                    01                011-350-0100008495-6           P                     02                     02                   821.27999999999997                                    236.0                                                 NULL     NULL     NULL     NULL     0                 2003-02-07 00:00:00.000                                NULL       NULL       CANC. ADU AMERICA 001-35146                        CAMTEX        2003-02-18 00:00:00.000

cabrec_numrecibo detrec_estadoreg detrec_item detrec_emisioncheque detrec_tipodoc_concepto detrec_numdocumento detrec_carabo detrec_forcan detrec_tdqc detrec_ndqc detrec_tipocajabanco detrec_cajabanco1 detrec_numctacte               detrec_adicionactacte detrec_monedadocumento detrec_monedacancela detrec_importesoles                                   detrec_importedolares                                 MOV_COD1 MOV_COD2 MOV_COD3 MOV_COD4 detrec_contadispo detrec_fechacancela                                    MOV_REFERE MOV_CENCOS detrec_observacion                                 usuariocodigo fechaact                                               
---------------- ---------------- ----------- -------------------- ----------------------- ------------------- ------------- ------------- ----------- ----------- -------------------- ----------------- ------------------------------ --------------------- ---------------------- -------------------- ----------------------------------------------------- ----------------------------------------------------- -------- -------- -------- -------- ----------------- ------------------------------------------------------ ---------- ---------- -------------------------------------------------- ------------- ------------------------------------------------------ 
200581                            1           B                    01                      00100004981         A             T             59          8085294     B                    01                191-1148049-1-63               P                     02                     02                   340.82339999999999                                    98.219999999999999                                    NULL     NULL     NULL     NULL     0                 2003-02-18 00:00:00.000                                NULL       NULL       CTA.CTE.BCO CREDITO M.E. CLASICO F/. 4981          CAMTEX        2003-02-18 00:00:00.000

cabrec_numrecibo detrec_estadoreg detrec_item detrec_emisioncheque detrec_tipodoc_concepto detrec_numdocumento detrec_carabo detrec_forcan detrec_tdqc detrec_ndqc detrec_tipocajabanco detrec_cajabanco1 detrec_numctacte               detrec_adicionactacte detrec_monedadocumento detrec_monedacancela detrec_importesoles                                   detrec_importedolares                                 MOV_COD1 MOV_COD2 MOV_COD3 MOV_COD4 detrec_contadispo detrec_fechacancela                                    MOV_REFERE MOV_CENCOS detrec_observacion                                 usuariocodigo fechaact                                               
---------------- ---------------- ----------- -------------------- ----------------------- ------------------- ------------- ------------- ----------- ----------- -------------------- ----------------- ------------------------------ --------------------- ---------------------- -------------------- ----------------------------------------------------- ----------------------------------------------------- -------- -------- -------- -------- ----------------- ------------------------------------------------------ ---------- ---------- -------------------------------------------------- ------------- ------------------------------------------------------ 
200302                            1           B                    01                      00100011454         A             T             59          07061472    B                    02                011-350-0100008487-6           P                     02                     02                   4154.7799999999997                                    1187.0799999999999                                    NULL     NULL     NULL     NULL     0                 2003-01-24 00:00:00.000                                NULL       NULL       ADELANTO ORDEN DE COMPRA                           CAMTEX        2003-01-30 00:00:00.000

cabrec_numrecibo detrec_estadoreg detrec_item detrec_emisioncheque detrec_tipodoc_concepto detrec_numdocumento detrec_carabo detrec_forcan detrec_tdqc detrec_ndqc detrec_tipocajabanco detrec_cajabanco1 detrec_numctacte               detrec_adicionactacte detrec_monedadocumento detrec_monedacancela detrec_importesoles                                   detrec_importedolares                                 MOV_COD1 MOV_COD2 MOV_COD3 MOV_COD4 detrec_contadispo detrec_fechacancela                                    MOV_REFERE MOV_CENCOS detrec_observacion                                 usuariocodigo fechaact                                               
---------------- ---------------- ----------- -------------------- ----------------------- ------------------- ------------- ------------- ----------- ----------- -------------------- ----------------- ------------------------------ --------------------- ---------------------- -------------------- ----------------------------------------------------- ----------------------------------------------------- -------- -------- -------- -------- ----------------- ------------------------------------------------------ ---------- ---------- -------------------------------------------------- ------------- ------------------------------------------------------ 
200578                            1           B                    01                      00120369            A             T             59          7061465     B                    02                011-350-0100008495-6           P                     02                     02                   515.9267000000001                                     147.83000000000001                                    NULL     NULL     NULL     NULL     0                 2003-02-14 00:00:00.000                                NULL       NULL       CREDITO M.E. DIFERIDO                              CAMTEX        2003-02-18 00:00:00.000

cabrec_numrecibo detrec_estadoreg detrec_item detrec_emisioncheque detrec_tipodoc_concepto detrec_numdocumento detrec_carabo detrec_forcan detrec_tdqc detrec_ndqc detrec_tipocajabanco detrec_cajabanco1 detrec_numctacte               detrec_adicionactacte detrec_monedadocumento detrec_monedacancela detrec_importesoles                                   detrec_importedolares                                 MOV_COD1 MOV_COD2 MOV_COD3 MOV_COD4 detrec_contadispo detrec_fechacancela                                    MOV_REFERE MOV_CENCOS detrec_observacion                                 usuariocodigo fechaact                                               
---------------- ---------------- ----------- -------------------- ----------------------- ------------------- ------------- ------------- ----------- ----------- -------------------- ----------------- ------------------------------ --------------------- ---------------------- -------------------- ----------------------------------------------------- ----------------------------------------------------- -------- -------- -------- -------- ----------------- ------------------------------------------------------ ---------- ---------- -------------------------------------------------- ------------- ------------------------------------------------------ 
200571                            1           B                    01                      00100027888         A             T             59          4439743     B                    01                191-1149199-0-69               P                     01                     01                   229.09999999999999                                    65.644699140401144                                    NULL     NULL     NULL     NULL     0                 2003-02-14 00:00:00.000                                NULL       NULL       DIFERIDO M.N. CREDITO                              CAMTEX        2003-02-14 00:00:00.000
200571                            2           B                    01                      00100027898         A             T             59          4439743     B                    01                191-1149199-0-69               P                     01                     01                   16.0                                                  4.5845272206303722                                    NULL     NULL     NULL     NULL     0                 2003-02-14 00:00:00.000                                NULL       NULL       DIFERIDO M.N. CREDITO                              CAMTEX        2003-02-14 00:00:00.000


select * from te_detallerecibos where detrec_ndqc like '654'

cabrec_numrecibo detrec_estadoreg detrec_item detrec_emisioncheque detrec_tipodoc_concepto detrec_numdocumento detrec_carabo detrec_forcan detrec_tdqc detrec_ndqc detrec_tipocajabanco detrec_cajabanco1 detrec_numctacte               detrec_adicionactacte detrec_monedadocumento detrec_monedacancela detrec_importesoles                                   detrec_importedolares                                 MOV_COD1 MOV_COD2 MOV_COD3 MOV_COD4 detrec_contadispo detrec_fechacancela                                    MOV_REFERE MOV_CENCOS detrec_observacion                                 usuariocodigo fechaact                                               
---------------- ---------------- ----------- -------------------- ----------------------- ------------------- ------------- ------------- ----------- ----------- -------------------- ----------------- ------------------------------ --------------------- ---------------------- -------------------- ----------------------------------------------------- ----------------------------------------------------- -------- -------- -------- -------- ----------------- ------------------------------------------------------ ---------- ---------- -------------------------------------------------- ------------- ------------------------------------------------------ 
200323                            1           B                    01                      00200001514         A             T             59          654         B                    02                011-350-0100008487-6           P                     02                     02                   204.66863999999998                                    58.409999999999997                                    NULL     NULL     NULL     NULL     0                 2003-01-23 00:00:00.000                                NULL       NULL       MALLA                                              CAMTEX        2003-01-30 00:00:00.000

(1 filas afectadas)

cabrec_numrecibo detrec_estadoreg detrec_item detrec_emisioncheque detrec_tipodoc_concepto detrec_numdocumento detrec_carabo detrec_forcan detrec_tdqc detrec_ndqc detrec_tipocajabanco detrec_cajabanco1 detrec_numctacte               detrec_adicionactacte detrec_monedadocumento detrec_monedacancela detrec_importesoles                                   detrec_importedolares                                 MOV_COD1 MOV_COD2 MOV_COD3 MOV_COD4 detrec_contadispo detrec_fechacancela                                    MOV_REFERE MOV_CENCOS detrec_observacion                                 usuariocodigo fechaact                                               
---------------- ---------------- ----------- -------------------- ----------------------- ------------------- ------------- ------------- ----------- ----------- -------------------- ----------------- ------------------------------ --------------------- ---------------------- -------------------- ----------------------------------------------------- ----------------------------------------------------- -------- -------- -------- -------- ----------------- ------------------------------------------------------ ---------- ---------- -------------------------------------------------- ------------- ------------------------------------------------------ 
200287                            1           B                    01                      00662855            A             T             59          7061436     B                    01                191-1148049-1-63               P                     02                     02                   506.66494                                             145.00999999999999                                    NULL     NULL     NULL     NULL     0                 2003-01-13 00:00:00.000                                NULL       NULL       VEXILLAPAGO POR REPOSICIÓN                         CAMTEX        2003-01-30 00:00:00.000