--select * from contaprueba.dbo.USUARIO

SELECT MEN_USU_COBR.USU_CODIGO, MEN_USU_COBR.EMP_CODIGO,  
	MENU_COBR.MEN_CODEDIT, MEN_USU_COBR.MEN_HAB  
	FROM USUARIODET As MEN_USU_COBR, MENU AS MENU_COBR  
WHERE (((MEN_USU_COBR.MEN_CODIGO)=[MENU_COBR].[MEN_CODIGO])) 
	AND   MEN_USU_COBR.USU_NOMBRE='guest' And MEN_USU_COBR.EMP_CODIGO='20293847038'

select * from USUARIODET